@ControllerAPI_HostAddress = http://localhost:5010/api

GET {{ControllerAPI_HostAddress}}/weatherforecast
Accept: application/json

###

GET {{ControllerAPI_HostAddress}}/User
Accept: application/json

###

GET {{ControllerAPI_HostAddress}}/User/1
Accept: application/json

###

POST {{ControllerAPI_HostAddress}}/User
Accept: application/json
Content-Type: application/json

{
  "id": 3,
  "username": "siriwan",
  "email": "siriwan@email.com",
  "fullname": "Siriwan Jaidee"
}

###

PUT {{ControllerAPI_HostAddress}}/User/3
Accept: application/json
Content-Type: application/json

{
  "id": 3,
  "username": "somjai",
  "email": "somjai@email.com",
  "fullname": "Somjai Jaidee"
}

###

DELETE {{ControllerAPI_HostAddress}}/User/3
Accept: application/json
Content-Type: application/json

###