@StoreAPI_HostAddress = http://localhost:5135/api

GET {{StoreAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{StoreAPI_HostAddress}}/Product/testconnectdb
Accept: application/json

###

GET {{StoreAPI_HostAddress}}/Product
Accept: application/json

###
